### ISSUE TITLE
bootloader entry point

### ISSUE THREAD

**Issue by qkenr7895** [ucsb-seclab/BootStomp#11]
I'm sorry to bother you with this simple question.

I have a bootloader that I want to find a vulnerability, so I am testing it with the bootloaders you provided.

For some reason, my ida couldn't decompile if it was 32 bits, so I did huawei's bootloader

The problem is that I need to specify an entry point before running find_tint.py, but I don't know this

I couldn't find the satisfied answer because of my lack of search skills.

Could you tell me how you designated the entry point for the bootloader?

**Comment by tallpid** [comment]
Usually it is a matter of static analysis - you need to find where most calls are started and where there is no other reference to your potential "main". Just try to search for this. From the other point, i don't understand why do you need "main" specifically. In a context of symbolic execution you need to find an "entry point" (nothing like actual main) of the interesting function, like memory management or verified boot

**Comment by qkenr7895** [comment]
Thank you for your kind and quick reply.

The reason why I asked for bootloader's entry point was because of the error shown in the picture below.

    list index out of range
    Traceback (most recent call last):
      File "D:\software\IDA 6.8\python\idaapi.py", line 541, in IDAPython_ExecScript
         execfile(script, g)
      File "D:/src/BootStomp-master/taint_analysis/find_taint.py", line 29, in <module>
        get_taint_sink_memcpy.get_sinks()
      File "D:/src/BootStomp-master/taint_analysis\find_taint_sinks.py", line 183, in get_sinks
        self.list_potential_memcpy()
      File "D:/src/BootStomp-master/taint_analysis\find_taint_sinks.py", line 91, in list_potential_memcpy
        function_info = helper.functions_info[function_index]
    IndexError: list index out of range

The qualqumm where ELF Header exists did not show the error above, so I thought I need an entry point.

Anyway, thank you for your good comments.

I tried to change the direction and solve the above error itself, and there was an article with the same problem, so I solved it by referring to the article.

https://github.com/ucsb-seclab/BootStomp/issues/3

I think it's going well now.

Thank you for your research.
