### ISSUE TITLE
how find_taint.py work with out IDA?

### ISSUE THREAD

**Issue by takboo** [ucsb-seclab/BootStomp#2]
the code in find_taint.py seems like it work with two type of environment: in ida and in angr.
the code only work in angr like this:

```python

import sys
import angr
import archinfo
import ipdb
import helper

# The 'main' guy

if __name__ == "__main__":
    filename = sys.argv[1]
    opts = {'main_opts': {'custom_arch': archinfo.arch_arm.ArchARM}}
    project = angr.Project(filename, load_options=opts)
    cfg = project.analyses.CFGFast(resolve_indirect_jumps = True, show_progressbar = True)
    helper.populate_method_info_angr()

```
on the line 5 in code above, imported helper. 
then in helper, it import idaapi and idauntils. 
because of this. it must work in ida, so why bother set two type of code?
it this a bug, or just some unfinished job?

**Comment by dipanjan** [comment]
Neither a bug or nor an unfinished job. Rather it's a leftover from the early phase of the effort. Must not interfere with the execution when loaded in IDA v6.95.
