### ISSUE TITLE
How to make BootStomp support X86

### ISSUE THREAD

**Issue by sky8336** [ucsb-seclab/BootStomp#7]
hi
I have some questions to ask.
I don't know how to use the tainted path, and what is the address 0x5319cL? How could I use this address to found the function name.
Thanks.

..
17)
===================== Start Info path =====================
Dereference address at: **0x5319cL**
Reason: at location 0x5319cL a tainted variable is dereferenced and used as address.
...
Tainted Path 
----------------
0x52f3cL -> 0x52f78L -> 0x52f8cL -> 0x52fb8L -> 0x52fc8L -> 0x52fecL -> 0x53000L -> 0x53014L -> 0x5301cL -> 0x53030L -> 0x53044L -> 0x53050L -> 0x5305cL -> 0x53068L
===================== End Info path =====================

**Comment by badnack** [comment]
Hi,
a tainted path represent the path from a source of taint (e.g., reading from hard-drive) to the sink of taint (e.g., strcpy). Usually a tainted path is a path to trigger to cause a crash or find a vulnerability. Each address in a tainted path is the address of a basic block.

The address 0x5319 is the address of the basic block where a tainted variable (e.g., influenced by user input) was dereferenced. To find the function, just jump at that basic block and see what's the function it belongs to.

For more info about tainted path and produced alarms, please refer to this paper https://www.usenix.org/system/files/conference/usenixsecurity17/sec17-redini.pdf

**Comment by sky8336** [comment]
Thanks for your help. "Just jump at that basic block "  means jump using IDA PRO, right?  Could I find the function without IDA PRO?

**Comment by badnack** [comment]
yes. You can use angr as alternative.

**Comment by sky8336** [comment]
Thanks. Another question: how to prepare taint info like "evaluation/huawei_p8/taint_info.txt".  How to get "method_name, method_addr, caller_name, caller_addr ..."? Is there any tool for that?

**Comment by dipanjan** [comment]
I can spot a little inconsistency there. What we refer as `taint_source_sink.txt` appears as `taint_info.txt` in the evaluation artifacts. How it can be generated is detailed [here](https://github.com/ucsb-seclab/BootStomp#automatic-detection-of-taint-sources-and-sinks).

**Comment by sky8336** [comment]
Does it mean that we could only generate it with IDA? 
Have you ever tried to generate taint_source_sink.txt without IDA. I try to run the python in the command line. It takes a long time.

$ python taint_analysis/find_taint.py bootloaders/huawei_p8/fastboot.img 
WARNING | 2017-11-23 09:47:44,033 | cle.blob | No custom_entry_point was specified for blob, assuming 0
WARNING | 2017-11-23 10:04:59,022 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000000_126_32{UNINITIALIZED}>
 37% |########################################                                                                    | Elapsed Time: **0:29:05** ETA:  0:48:09
39% |##########################################                                                                  | Elapsed Time: **0:55:34** ETA:  1:24:32

**Comment by dipanjan** [comment]
You are trying to use `angr` which won't work. Most probably it'll fail immediately after CFG construction, if `CFGFast()` doesn't fail itself. We only support IDA at the moment.

**Comment by sky8336** [comment]
What are the challenges to support angr? Do you have any suggestions?
How to get unlock_addr?
Thanks!

**Comment by dipanjan** [comment]
We heavily use IDA's decompiler API to identify taint seeds and sinks. angr, at least at the time of development, didn't have any decompiler support.

Referring to section 7.3 of the [paper](https://www.usenix.org/system/files/conference/usenixsecurity17/sec17-redini.pdf),

> To run this experiment, we begin with the manually identified unlocking functionality, as described in Section 6.2, and locate paths that reach automatically identified writes to the device’s storage.

`unlock_addr` is the address of the handler method (identified by manual analysis) for the unlocking functionality.

**Comment by sky8336** [comment]
When I use IDA to run find_taint.py for huawei_p8, the taint_source_sink.txt has nothing but some strings like "base_addr:".  I just drag and drop  fastboot.img to IDA window, and then run find_taint.py. Is there anything wrong with that?? Could you provide more details for loading binary and running find_taint.py? Thanks.
IDA version: 6.95

**Comment by sky8336** [comment]
Since we have the bootloader's source code,  could we pick up the seeds and sinks manully?  I just disassembly the binary, and get the following information:
   method_name, method_addr, caller_name, caller_addr,  arg_cnt, non_string_args_list, 

But I don't know how to prepare the following information:
   taint_addr, taint_bb_addr, log_message_xref_addr, log_message_addr
Is this necessary ?

Since we have source code, could you offer some suggestions?

**Comment by badnack** [comment]
Yes, you need that info. As I mentioned before, you should read this [article](https://www.usenix.org/system/files/conference/usenixsecurity17/sec17-redini.pdf), it explains in details what those fields mean and how to find them.

**Comment by sky8336** [comment]
OK, thanks.

**Comment by sky8336** [comment]
Does BootStomp support x86_64 arch?

**Comment by dipanjan** [comment]
We didn't try that. In principle it should as long as IDA and angr support that architecture. However, at least those IDA scripts contain certain ARM specific heuristics.

**Comment by badnack** [comment]
Bootstomp supports ARM 32 and AARCH64

**Comment by sky8336** [comment]
Could you estimate what should we do if we want to make Bootstomp support X86.

**Comment by badnack** [comment]
There are mainly two things you should take care of: instruction offsets and stack. As sometimes angr cannot lift some instructions, you might need to skip few of those. In ARM, AARCH64 and MIPS, you know that an instruction is long n bytes, so you can just add x*n bytes to PC to skip x instructions. In x86 the instruction length is variable, so you might need to write an ad-hoc function to estimate the length of the current assembly instruction. The second problem is the stack. Bootstomp has to retrieve the value of some function parameters as well as set the return values (in case of taint propagation in case you don't want to follow a call). While in ARM and AARCH64 you know where these values are (as long as the number of parameters passed to a function is less then a threshold), in x86 you should retrieve/set them  from/to the stack. Besides these two issues, I don't see any major problems in making Bootsomp working with x86 binaries.

**Comment by sky8336** [comment]
As I am new to python, the question is not clear to me on how I can find out the code related to the two things(instruction offsets and stack) . I found it maybe in _coretaint.py, but not sure what function is related to the two things. All of the codes related to the two things are in bootstomp, you didn't modify the code of angr, right? 
Moreover, it is a little difficult for me to determine where the ARM specific heuristics contained by those IDA scripts sit. I think some of them is contained in get_taint_source.heuristic_search_keywords_in_log_messages().
Thanks for any help given.
thank you!
